import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import '../services/firebase'
import Image from 'next/image'
import logo from '/assets/logo.svg'
import googleIcon from '/assets/google-icon.svg'
import { CopyButton } from '../components/copyButton'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <aside>
        <Image
          src="https://via.placeholder.com/200/0000FF/808080 "
          alt="image"
          width={200}
          height={200}
        />

        <h1 className="text-3xl font-bold">Every question has an answer</h1>
        <h3>learn and share knowledge with every one</h3>
      </aside>
      <main className={styles.main}>
        <Image src={logo} alt="logo" />
        <button>
          <Image src={googleIcon} alt="askCanada" />
          Create a room with Google
        </button>
        <div>or</div>
        <form>
          <input type="text" placeholder="Type the rooom code" />
          <button type="submit">Enter</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <CopyButton text="#343434" />
      </footer>
    </div>
  )
}

export default Home
