import type { NextPage } from 'next'
import Head from 'next/head'
import '../services/firebase'
import Image from 'next/image'
import logo from '/assets/logo.svg'
import googleIcon from '/assets/google-icon.svg'
import { CopyButton } from '../components/copyButton'
import { Button } from '../components/button'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>askCanada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="sm:mb-24 xl:mb-32 lg:flex">
        <aside className="relative flex-1 max-w-screen-sm mx-auto lg:mx-0 lg:max-w-none gap-10 lg:gap-8 text-sm bg-red-500 h-full h-[100vh] flex flex-col">
          <Image
            src="https://via.placeholder.com/200/0000FF/808080 "
            alt="image"
            width={200}
            height={200}
          />

          <h1 className="text-3xl font-bold">Every question has an answer</h1>
          <h3>learn and share knowledge with every one</h3>
        </aside>
        <main className="flex-1 relative z-10 flex flex-col items-center justify-center lg:pt-10 max-w-screen-sm mx-auto lg:max-w-2xl lg:mx-0 lg:pr-20 mb-12 sm:mb-16 lg:mb-0 xl:ml-6">
          <div className="w-80 flex flex-col">
            <i className="pb-8">
              <Image src={logo} alt="logo" />
            </i>
            <Button type="button" onClick={() => {}}>
              <i className="pr-1.5 relative w-6">
                <Image src={googleIcon} alt="askCanada" />
              </i>
              <span className="flex self-center">
                Create a room with Google
              </span>
            </Button>
            <div>or</div>
            <form>
              <input type="text" placeholder="Type the rooom code" />
              <Button
                fullWidth
                variant="outline"
                type="submit"
                onClick={() => {}}
              >
                Enter
              </Button>
            </form>
          </div>
        </main>
      </div>

      <footer>
        <CopyButton text="#343434" />
      </footer>
    </>
  )
}

export default Home
